### PR TITLE
Raise the stake a little bit

### PR DESCRIPTION
**Pull request by stripthis**

### CODE REVIEW

**Comment by caseyw** [comment]
Seems legit.

**Comment by umer936** [comment]
Considered. Won't merge as I think the stakes for this plugin should remain at the app level. 

There are various tools for a similar implementation at the filesystem root level noted in the README.

**Comment by umer936** [comment]
Additionally I'm not sure the best way to test your implementation lol.

Not sure if it would work correctly on various OSes (Windows, different Linux distros, OS X) whereas I'd like the plugin to remain platform-agnostic. 

Thanks for the contribution though!

**Comment by stripthis** [comment]
If people are interested in forking this project, please get in touch. The maintainers are clearly out of touch and lost all my trust in this project.

**Pull request closed without merging**
